export default {
    "nav": {
        "home": "Home",
        "about": "About",
        "solutions": "Solutions",
        "projects": "Projects",
        "contact": "Contact"
    },
    "nav2": {
        "about": "about",
        "solutions": "solutions",
        "projects": "projects",
        "contact": "contact",
        "terms": "terms",
        "regulations": "regulations",
        "deletAcc": "removeaccount"
    },
    "btn": {
        "quote": "Request a Quote",
        "knowSolutions": "Explore Our Solutions",
        "clickAndKnow": "Click and Learn More",
        "toKnow": "To Know",
        "send": "Send",
        "toSchedule": "Schedule",
        "sendQuestion": "Send Your Question"
    },
    "logos": {
        "title": "Some brands that already have Recicletool",
        "text": "Bring your company into this movement, a simple step that can lead to great positive impacts!"
    },
    "products": {
        "title": "Check out our current projects",
        "cokeTitle": "Coca-Cola",
        "cokeText": "Deposit Coca-Cola plastic returnable packaging and get discounts on the purchase of a new Coca-Cola product.",
        "heinekenTitle": "Heineken",
        "heinekenText": "Recycle any packaging and receive discounts on the purchase of Heineken products."
    },
    "cta": {
        "title": "Be part of this change",
        "text": "Get in touch with us and join the group of brands working for sustainability! Together, we can make a difference."
    },
    "footer": {
        "terms": "Terms",
        "regulation": "Regulations",
        "who": "Who We Are",
        "copyright": "© 2023 Recicletool. All rights reserved."
    },
    "home": {
        "top": {
            "heading": "We use computer vision, identify packaging, and generate gravimetry data in a waste Big Data for environmental management.",
            "text": "We develop environmental solutions for reverse logistics of packaging in the post-consumer stage. That is, when the consumer has already used their product and only the empty packaging remains, which must be sent for proper final disposal."
        },
        "solutions": {
            "title": "Recicletool Machines",
            "machines": {
                "standardText": "Capacity of 768 L, LED for 32-inch advertisements, two inputs for packaging, and a 15.6-inch touchscreen for user operation.",
                "standardCta": "Learn More",
                "maxText": "Capacity of 768 L, LED for 32-inch advertisements, one input for packaging, and a 15.6-inch touchscreen for user operation.",
                "plusText": "Capacity of 1,843 L, LED for 43-inch advertisements, one input for packaging, and a 15.6-inch touchscreen for user operation.",
                "otherTitle": "Others",
                "otherText": "We develop other self-service equipment for selling beer and carbonated beverages, such as solar refrigerators, glass crushers for bars, and smart lockers for collecting electronics and logistics."
            }
        },
        "banner": {
            "titleFirstLine": "Together for",
            "titleSecondLine": ["recycling", "circularity", "reverse logistics"]
        },
        "data": {
            "columnLeft": "Over 11,000 packages collected in just one machine in 24 months.",
            "columnCenter": "Curiosities: 70.37% of recyclers are men and the days with the most recycling are Wednesdays.",
            "columnRight": "Recycling discount coupons generated by the machine increase brand sales by up to 20% at partner supermarkets.",
            "footer": "These are just some of the data collected in the Waste Collection Reports from our clients, which show the potential of implementing the machines in self-flow environments of consumers, especially in supermarkets."
        },
        "benefits": {
            "title": "Benefits for your company",
            "destination": "Correct disposal of packaging waste in the post-consumer stage.",
            "fidelization": "Customer loyalty through recycling, which generates discount coupons.",
            "growth": "Increase in sales of products linked to the recycling process in partner supermarkets.",
            "conformity": "Compliance with environmental legislation through the delivery of detailed reports on the waste collected."
        }
    },
    "about": {
        "top": {
            "heading": "We are Recicletool, a startup that offers environmental solutions in the area of reverse logistics for packaging.",
            "text": "Environmental sustainability solutions that combine compliance with the law and support for brand sales efforts in the market through customer loyalty through recycling.",
            "slider": [
                {
                    "title": "Machine that collects cans and bottles generates rewards in Greater Recife",
                    "text": "Two machines are set to start operating in November. A corresponding credit is generated for each package deposited."
                }
            ]
        },
        "story": {
            "tag": "Recicletool's Story",
            "heading": "Our goal is to help companies deal responsibly with waste from final product consumption.",
            "text": "We have developed an innovative and Brazilian technology: machines installed in supermarkets and public places that collect recyclable materials. They identify what has been deposited and reward the user based on the quantity of material. In other words, your consumer can make money from recycling actions, turning their environmental awareness into money. Additionally, we are committed to reverse logistics, which involves environmental concern in properly disposing of waste from industrialized products, such as packaging. We work with both end consumers and industries, assisting in the creation of Solid Industrial Waste Management Plans that promote environmental practices and comply with the law. Our work is not limited to complying with solid waste legislation. We also contribute significantly to environmental impact mitigation and risk reduction in this area. Join us on the mission to make the world cleaner and more sustainable.",
            "footer": "We are also a corporate solution for the obligations established by the National Solid Waste Policy Law (Law 12.305/2010) for Brazilian industries. We strongly act on mitigating environmental liabilities, reducing exposure to risks in this area."
        },
        "newsText": "Some stories about Recicletool's solutions featured in the media below:",
        "impact": {
            "heading": "Impact of machines on companies:",
            "text": "Check out some of the data collected with the implementation of machines in supermarkets:",
            "dataColect": "11 thousand",
            "textColect": "Over 11 thousand packages collected in just one machine in 24 months.",
            "textCuriosity": "Curiosities: 70.37% of recyclers are men, and the days when recycling is most active are Wednesdays.",
            "textOrders": "Recycling discount coupons generated by the machine increase brand sales by up to 20% at partner supermarkets.",
            "dataArcomix": "5 thousand",
            "textArcomix": "From February 2021 to March 2022, over 5 thousand residues were collected only in machines installed at Arcomix supermarket in Pernambuco."
        }
    },
    "machines": {
        "top": {
            "heading": "Your company encouraging proper waste disposal and environmental awareness in areas with high consumer traffic.",
            "text": "Recicletool is capable of collecting products ranging from food to personal hygiene and cleaning. In this set, the products that can be part of Recicletool's reverse logistics process are mainly those with a cylindrical shape or similar to a cylinder and that must have a barcode."
        },
        "tutorial": {
            "headerTitle": "See the step-by-step on how to use our machines",
            "headerText": "Using optical reading technology, the machine identifies the residues deposited by customers, registering them for recycling financial credit.",
            "step1Title": "Registration in the app",
            "step1Text": "In one of our machines, the user will find a QR Code. By pointing the camera, they will be directed to the registration link, where they start the recycling journey.",
            "step2Title": "Deposit of packages",
            "step2Text": "After registering, the user inserts the registered phone on the machine's touch screen and then deposits the empty packages in the machine's circular entrance.",
            "step3Title": "Finishing the process",
            "step3Text": "When inserting the package into the machine, the user must click on the scan button on the touch screen and wait for the message to finalize the process.",
            "step4Title": "Follow the actions",
            "step4Text": "Using the machine's app, the user can track their recycling history and access rewards for their initiative. And the company can track product entries and learn more about its customers."
        },
        "machinesSubHeading": "Solutions",
        "machinesHeading": "Get to know our machines",
        "dataHeading": "Some of the cities where they can be found"
    },
    "contact": {
        "top": {
            "heading": "Contact us",
            "text": "For proposals, suggestions, and partnerships, send an email to td@recicletool.com or send a message.",
            "labelName": "Name",
            "labelMessage": "Message",
            "placeholderMessage": "Enter your message....",
            "checkLabel": "I accept the",
            "checkTermsLabel": "terms of service"
        },
        "logosHeading": "Some brands already using Recicletool",
        "icons": {
            "meet": "Schedule a meeting",
            "talkToUs": "Talk to Us"
        },
        "faq": {
            "heading": "Frequently Asked Questions",
            "question1": "How many bottles fit inside a machine?",
            "answer1": "The capacity of a Recicletool Standard machine is 0.768m³, corresponding to 768L. Theoretically, it corresponds to 384 600ml bottles whole or 182.4kg of glass.",
            "question2": "What is the machine's energy consumption?",
            "answer2": "On average, the machines consume 5 kWh/month if operated for 8 hours a day for 01 month.",
            "question3": "What are the dimensions of the Recicletool Standard, Max, and Plus machines?",
            "answer3": "Standard - 185cm x 80cm x 80cm. Max - 185cm x 90cm x 90cm. Plus - 210cm x 135cm x 100cm",
            "question4": "How do I delete my account?",
            "answer4": "To delete your account",
            "answer42": "click here and follow the instructions",
            "ctaLabel": "Still have a question?"
        }
    },
    "projects": {
        "heading": "Select a project",
        "text": ""
    },
    "infoMachine": {
        "plus": {
            "specification": {
                "dimensions": "Dimensions: 1.915m (height) X 1.33m (width) X 0.99m (depth)",
                "list": [
                    "Weight: 242kg",
                    "Displacement: 04 casters on the machine base.",
                    "Voltage: (220V)",
                    "Consumption: 12 kWh/month (operating 12 hours a day)",
                    "Display: LED for advertising with 43 inches",
                    "Interaction: 15.6-inch touchscreen for user operation",
                    "Material: Galvanized steel base and custom branding according to your visual language.",
                    "Collection: PET packaging, aerosol spray, aluminum cans, high-density plastic packaging (cleaning products), glass bottles, etc.",
                    "Installation: 01 220V socket, Tempra 16A - industrial model.",
                    "NOTE: The equipment can only be installed in a covered area (indoor), away from moisture and direct sunlight."
                ]
            },
            "capacity": "Storage capacity: 1.843m³ corresponding to 1,843L. Theoretically, it corresponds to 921 600ml bottles whole or 437.5kg of glass, based on the weight of 475g of each 600ml bottle and discounting the area lost due to the irregular shape of the container."
        },
        "standardAndMax": {
            "specification": {
                "dimensions": "Dimensions: 1.85m (height) X 0.80m (width) X 0.80m (depth)",
                "list": [
                    "Weight: 170kg",
                    "Displacement: 04 casters on the machine base.",
                    "Voltage: (220V)",
                    "Consumption: 5kWh/month (operating 12 hours a day)",
                    "Display: LED for advertising with 32 inches",
                    "Interaction: 15.6-inch touchscreen for user operation",
                    "Material: Galvanized steel base and custom branding according to your visual language.",
                    "Collection: PET packaging, aerosol spray, aluminum cans, high-density plastic packaging (cleaning products), glass bottles, etc.",
                    "Installation: 01 220V socket, Tempra 16A - industrial model.",
                    "NOTE: The equipment can only be installed in a covered area (indoor), away from moisture and direct sunlight."
                ]
            },
            "capacity": "Storage capacity: 0.768m³ corresponding to 768L. Theoretically, it corresponds to 384 600ml bottles whole or 182.4kg of glass, based on the weight of 475g of each 600ml bottle and discounting the area lost due to the irregular shape of the container."
        },
        "other": {
            "specification": {
                "dimensions": "Self-Service Machine for Carbonated Beverages and Liquid Products",
                "list": [
                    "Equipment Height: 1.80m.",
                    "Diameter: 0.80m.",
                    "Voltage: (220V).",
                    "Energy Consumption: 148Kw/h per month.",
                    "Internet connection with sales performance alert.",
                    "Purchases via application."
                ]
            },
            "capacity": "Storage capacity: 02 50L beverage barrels."
        },
        "softwareText": "Smartphone application for Android and iOS that allows users to track their recycling credits, locate nearby recycling machines, withdraw waste credits, and access their profile with contact information. The system can also be accessed via the website for users without smartphones. \nFor companies, the app offers monitoring of the volume and location of contracted machines, filling notifications, and reports of collected waste."
    },
    "deletAccount": {
    "top": {
        "heading": "Delete Account",
    },
    "mid": {
        "heading": "By deleting your account",
        "content": ["We will no longer have access to your personal data.", "You will no longer have access to your coupons.", "You will no longer have access to your recycling history.", "It will not be possible to recover your account."],
        "how": "To delete your account, simply access the application of the program you are registered in and you will find this option on your profile page.",
    }
}
} as const